version: '3'
services:
  nginx:
    image: library/nginx:1.18-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - .data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot
  jupyterhub:
    image: jupyterhub/jupyterhub